name: bench_tomo_3d_nview_multidose_N_1gpu
model_type: SPECTModel
scale: 1
num_gpu: 0
manual_seed: 20020113
auto_resume: false

datasets:
  train:
    name: spect229_train_tomo_3d_nview_multidose_N_bench
    type: SPECTTrainDataset
    phase: train
    mode: poisson_thinning
    input_layout: volume
    dataroot_gt: /home/owen/code/BasicSR/datasets/SPECT229
    pattern_gt: "**/*_Proj4Filter.dat"
    views: 60
    height: 128
    width: 128
    dtype: uint16
    view_sampler:
      mode: n_views
      n_views: 60
      strategy: fixed
      start: 0
    pack_mode: 3d_depth
    max_value: 150.0
    gt_scale_factor: 1.0
    clip_max_value: false
    poisson_thinning_mode: same_dose
    poisson_thinning_k_choices: [2, 3, 4, 5]
    poisson_thinning_prob: 0.5
    poisson_thinning_random_swap: false
    poisson_thinning_round_mode: nearest
    start_idx: 4
    end_idx: 32
    num_worker_per_gpu: 0
    batch_size_per_gpu: 1
    pin_memory: false

network_g:
  type: UNet3DRes
  in_nc: 1
  out_nc: 1
  nc: [16, 32, 64, 128]
  nb: 2
  bias: false
  global_residual: true
  circular_depth: true
  act: relu

path:
  pretrain_network_g: null
  strict_load_g: true
  resume_state: null

train:
  pbar: false
  disable_cudnn: false
  amp:
    enable: false
    dtype: bf16
    loss_fp32: true
    use_scaler: false
  ema_decay: 0.999
  accumulation_steps: 1
  optim_g:
    type: AdamW
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
  scheduler:
    type: MultiStepLR
    milestones: [30]
    gamma: 1
  total_iter: 30
  warmup_iter: -1
  pixel_opt:
    type: PoissonNLLLoss
    loss_weight: 1.0
    reduction: mean
    eps: 1.0e-9
    max_value: 150.0
    norm_type: linear

logger:
  print_freq: 1
  save_checkpoint_freq: 1000
  use_tb_logger: false
  wandb: null

dist_params:
  backend: nccl
  port: 29500
