name: converged_planar_2d_2view
model_type: SPECTModel
scale: 1
num_gpu: 1
manual_seed: 20020113
auto_resume: true

datasets:
  train:
    name: xcat_train_planar_2d_2view
    type: SPECTTrainDataset
    phase: train
    mode: poisson_thinning
    input_layout: ap2
    dataroot_gt: datasets/spectH_XCAT_poisson_1x
    pattern_gt: "*.dat"
    views: 2
    dtype: float32
    height: 1024
    width: 256
    posterior_flip: true
    view_sampler:
      mode: opposite_pair
      offset: 1
    pack_mode: 2d_channel
    start_idx: 0
    end_idx: 96
    poisson_thinning_prob: 0.5
    poisson_thinning_random_swap: false
    poisson_thinning_round_mode: nearest
    gt_scale_factor: 1.0
    max_value: 150.0
    norm:
      type: linear
    gt_size: 64
    use_hflip: false
    use_rot: false
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 4
    pin_memory: true
    persistent_workers: true

  val:
    name: xcat_val_planar_2d_2view
    type: SPECTTrainDataset
    phase: val
    mode: paired
    input_layout: ap2
    dataroot_lq: datasets/spectH_XCAT_poisson_1x
    dataroot_gt: datasets/spectH_XCAT_ideal_1x
    pattern_gt: "*.dat"
    pattern_lq: "*.dat"
    views: 2
    dtype: float32
    height: 1024
    width: 256
    posterior_flip: true
    view_sampler:
      mode: opposite_pair
      offset: 1
    pack_mode: 2d_channel
    start_idx: 96
    end_idx: 100
    gt_scale_factor: 1.0
    max_value: 150.0
    norm:
      type: linear

network_g:
  type: UNetRes
  in_nc: 2
  out_nc: 2
  nc: [64, 128, 256, 512]
  nb: 4
  act_mode: R
  downsample_mode: strideconv
  upsample_mode: convtranspose
  bias: false
  global_residual: true

path:
  pretrain_network_g: null
  strict_load_g: true
  resume_state: null

train:
  ema_decay: 0.999
  pbar: true
  optim_g:
    type: AdamW
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000]
    restart_weights: [1]
    eta_min: 1.0e-5
  total_iter: 50000
  warmup_iter: -1
  pixel_opt:
    type: PoissonNLLLoss
    loss_weight: 1.0
    reduction: mean
    eps: 1.0e-9
    max_value: 150.0
    norm_type: linear

val:
  val_freq: 1000
  save_img: false
  eval_networks: [g, ema]
  save_best_ckpt: true
  best_metric: psnr_cnt_ema
  metrics:
    psnr_cnt:
      type: calculate_psnr_range
      domain: count
      data_range: 150.0
      crop_border: 0
      test_y_channel: false
      better: higher
    ssim_cnt:
      type: calculate_ssim_range
      domain: count
      data_range: 150.0
      crop_border: 0
      test_y_channel: false
      better: higher

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  keep_ckpt_num: 2
  keep_state_num: 2
  wandb: null


dist_params:
  backend: nccl
  port: 29500
