name: converged_planar_2d_1view
model_type: SPECTModel
scale: 1
num_gpu: 1
manual_seed: 20020113
auto_resume: true

datasets:
  train:
    name: spect229_train_planar_2d_1view
    type: SPECTTrainDataset
    phase: train
    mode: poisson_thinning
    input_layout: ap2
    dataroot_gt: datasets/SPECT229_projection_paired
    pattern_gt: "*.dat"
    views: 2
    dtype: float32
    height: 128
    width: 128
    posterior_flip: false
    view_sampler:
      mode: single_view
      view_indices: [0, 1]
    pack_mode: 2d_channel
    start_idx: 0
    end_idx: 6870
    poisson_thinning_prob: 0.5
    poisson_thinning_random_swap: false
    poisson_thinning_round_mode: nearest
    gt_scale_factor: 1.0
    max_value: 150.0
    norm:
      type: linear
    gt_size: 64
    use_hflip: false
    use_rot: false
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 2
    pin_memory: true
    persistent_workers: true

network_g:
  type: UNetRes
  in_nc: 1
  out_nc: 1
  nc: [64, 128, 256, 512]
  nb: 4
  act_mode: R
  downsample_mode: strideconv
  upsample_mode: convtranspose
  bias: false
  global_residual: true

path:
  pretrain_network_g: null
  strict_load_g: true
  resume_state: null

train:
  ema_decay: 0.999
  pbar: true
  optim_g:
    type: AdamW
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: 1.0e-5
  total_iter: 300000
  warmup_iter: -1
  pixel_opt:
    type: PoissonNLLLoss
    loss_weight: 1.0
    reduction: mean
    eps: 1.0e-9
    max_value: 150.0
    norm_type: linear

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  keep_ckpt_num: 2
  keep_state_num: 2
  wandb: null


dist_params:
  backend: nccl
  port: 29500
